config/routes.rb
Rails.application.routes.draw do


  root "home#index"

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  
  resources :bulletins do
    collection { get :search }
    resources :posts
    post "/posts/:post_id/good", to: "goods#good_toggle"
    post "/posts/:post_id/report", to: "reports#report_toggle"
  end

  get '/notifications/read_all' => 'notifications#read_all'

  resources :notifications

  devise_for :users
  
  resource :users, only: [:index] do
    collection { get :search }
  end

  get 'home/index'

  get '/home/update'

  get '/home/git'

  post '/tinymce_assets' => 'tinymce_assets#create'
  
  get "/knu/knu_world"
  
  post "/knu/key"
  
  ## 채팅 메세지 구현 By 상열 -----------------------------------------------------------------------------
  ## For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
  
  resources :users, only: [:index]
  resources :personal_messages, only: [:new, :create]
  resources :conversations, only: [:index, :show]

  
  get "/members/show" => "members#show"
  # --------------------------------------------------------------------------------------------------------

  resources :vote_comments
  resources :links do
    member do
      put "like", to:    "links#upvote"
      put "dislike", to: "links#downvote"
    end
  resources :vote_comments, only: [:create, :destroy]
  end


end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :receiver, class_name: 'User'

  has_many :personal_messages, -> { order(created_at: :asc) }, dependent: :destroy

  validates :author, uniqueness: {scope: :receiver}

  scope :participating, -> (user) do
    where("(conversations.author_id = ? OR conversations.receiver_id = ?)", user.id, user.id)
  end

  scope :between, -> (sender_id, receiver_id) do
    where(author_id: sender_id, receiver_id: receiver_id).or(where(author_id: receiver_id, receiver_id: sender_id))
  end

  def with(current_user)
    author == current_user ? receiver : author
  end

  def participates?(user)
    author == user || receiver == user
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
    before_action :set_conversation, except: [:index]
    before_action :check_participating!, except: [:index]

    def index
      @conversations = Conversation.participating(current_user).order('updated_at DESC')
      respond_to do |format|
        format.html
        format.js
      end
    end
    
    def show
      @conversation = Conversation.find_by(id: params[:id])
      @personal_message = PersonalMessage.new
      
    end
    
    private

    def set_conversation
      @conversation = Conversation.find_by(id: params[:id])
    end
    
    def check_participating!
      redirect_to root_path unless @conversation && @conversation.participates?(current_user)
    end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<div class="row" bgcolor="white" onMouseOver="this.style.backgroundColor='#ECECEC'" onMouseOut="this.style.backgroundColor='#FFFFFF'">
  <div align="center" style="padding: 10px 10px 10px 10px; border-bottom: 1px solid gray;" class="col-2 col-md-3 board_nickname_etc"><%= online_status conversation.with(current_user) %></div>
  <div style="padding: 10px 10px 10px 10px; border-bottom: 1px solid gray;" class="col-7 col-md-7">
    <%= link_to conversation_path(conversation) do %>
      <%= content_tag(:div, conversation.personal_messages.last.body.truncate(50), class: "board_title_etc") %>
    <% end %>
    </div>
  <div align="center" style="padding: 10px 10px 10px 10px; border-bottom: 1px solid gray;" class="col-3 col-md-2"><%= "#{time_ago_in_words(conversation.created_at)} 전" %></div>
</div>

app/views/conversations/index.html.erb
<div class="board" style="background: url('/img/title_img_4.jpg') no-repeat center center/cover scroll;"><span style="color: white; background:rgba(0,0,0,0.6); padding: 10px; border-radius: 10px;"><%= link_to '쪽지함', conversations_path, class: "board_title" %></span></div>

<% #경고메세지 출력 (아이디, 비밀번호 잘못 칠 시 등등...) %>
<% if alert %>
    <div class="alert alert-danger tlert-dismissible fade show text-center" style="padding: 10px; background-color: #FF4B5C; color: white; border-radius: 0; margin-bottom: 0; border: 0">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
    <% elsif notice %>
    <div class="alert alert-danger tlert-dismissible fade show text-center" style="padding: 10px; background-color: #43AC6A; color: white; border-radius: 0; margin-bottom: 0; border: 0">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
<% end %>

<div class="container" style="margin-bottom: 100px;">
    <div class="row" style="margin-top: 30px;">
        <div style="padding: 10px 10px 10px 10px; border-bottom: 3px solid #D5D5D5; background: #EFEFEF;" class="col-2 col-sm-2 col-md-3" align="center">보낸이</div>
        <div style="padding: 10px 10px 10px 10px; border-bottom: 3px solid #D5D5D5; background: #EFEFEF;" class="col-7 col-sm-5 col-md-7" align="center">쪽지내용</div>
        <div style="padding: 10px 10px 10px 10px; border-bottom: 3px solid #D5D5D5; background: #EFEFEF;" class="col-3 col-sm-3 col-md-2" align="center">최초 개설시간</div>
    </div>

    <div id="conversations">
      <%= render @conversations %>
    </div>
</div>

app/views/conversations/index.js.erb
$('#conversations').replaceWith('<%= j render @conversations %>');

app/views/conversations/show.html.erb
<div class="board" style="background: url('/img/title_img_4.jpg') no-repeat center center/cover scroll;"><span style="color: white; background:rgba(0,0,0,0.6); padding: 10px; border-radius: 10px;"><%= link_to '쪽지 보내기', '/users', class: "board_title" %></span></div>
<div class="container" style="margin-bottom: 100px;">
<h1 align="center" style="margin-top: 30px;"><%= @conversation.with(current_user).nickname %></h1><hr/>

<div id="conversation-main">
  <div id="conversation-body" data-conversation-id="<%= @conversation.id %>">
      <%= render @conversation.personal_messages %>
  </div>

  <%= form_for @personal_message do |f| %>
    <%= hidden_field_tag 'conversation_id', @conversation.id %>

  <div class="row">
    <div class="col-9 col-sm-10 col-md-11" align="right">
    <%= f.text_area :body, class: "form-control" %>
    </div>
    <div class="col-2 col-sm-1 col-md-1" align="left">
    <%= f.submit :전송, class: "btn btn-outline-warning" %>
    </div>
  </div>
  <% end %>
</div>
</div>