config/routes.rb
Rails.application.routes.draw do


  root "home#index"

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  
  resources :bulletins do
    collection { get :search }
    resources :posts
    post "/posts/:post_id/good", to: "goods#good_toggle"
    post "/posts/:post_id/report", to: "reports#report_toggle"
  end

  get '/notifications/read_all' => 'notifications#read_all'

  resources :notifications

  devise_for :users
  
  resource :users, only: [:index] do
    collection { get :search }
  end

  get 'home/index'

  get '/home/update'

  get '/home/git'

  post '/tinymce_assets' => 'tinymce_assets#create'
  
  get "/knu/knu_world"
  
  post "/knu/key"
  
  ## 채팅 메세지 구현 By 상열 -----------------------------------------------------------------------------
  ## For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
  
  resources :users, only: [:index]
  resources :personal_messages, only: [:new, :create]
  resources :conversations, only: [:index, :show]

  
  get "/members/show" => "members#show"
  # --------------------------------------------------------------------------------------------------------

  resources :vote_comments
  resources :links do
    member do
      put "like", to:    "links#upvote"
      put "dislike", to: "links#downvote"
    end
  resources :vote_comments, only: [:create, :destroy]
  end


end

app/models/user.rb
class User < ApplicationRecord
  after_create :assign_default_role
  # 검색엔진
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  
  paginates_per 6
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  acts_as_reader
  acts_as_voter
  has_many :vote_comments
  has_many :links
  has_many :posts
  has_many :bulletins
  has_many :goods
  has_many :gooded_posts, through: :goods, source: :post
  #User에서 liked_posts를 가져오는데 이건 likes를 베이스로 가져오고
  #post인 애들만 보여준다
  has_many :reports
  has_many :reported_posts, through: :reports, source: :post
  
  has_many :comments
  has_many :notifications
  
  def is_good?(post)
    Good.find_by(user_id: self.id, post_id: post.id).present?
  end
  
  def is_report?(post)
    Report.find_by(user_id: self.id, post_id: post.id).present?
  end

  def assign_default_role
    add_role(:student)
  end

  # 닉네임 중복검사
  validates_uniqueness_of :nickname
  
  # 채팅 by Sy 180815
  def name
    email.split('@')[0]
  end
  
  has_many :authored_conversations, class_name: 'Conversation', foreign_key: 'author_id'
  has_many :received_conversations, class_name: 'Conversation', foreign_key: 'received_id'
  has_many :personal_messages, dependent: :destroy

  def online?
    !Redis.new.get("user_#{self.id}_online").nil?
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def create
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    
    def search
      @users = User.search(params[:q]).records
      render action: "index"
    end
    
    def index
        @users = User.all.where.not(id: current_user)
        @users = User.order("created_at DESC").page params[:page]
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<div style="margin-left: 20px; margin-top: 10px;" class="card col-md-5 col-sm-3 hidden-xs-down">
  <div class="card-block">
    <h3 class="card-title"><%= content_tag(:div, user.nickname, class: "card-user_nickname") %></h3>
    <p class="card-text">한마디 : 
    <% if user.description.empty? %>
    <span style="color: blue">한마디를 적지 않으셨습니다.</span>
    <% else %>
    <%= user.description %>
    <% end %>
    </p>
    <%= link_to '쪽지 보내기', new_personal_message_path(receiver_id: user), class: "btn btn-primary" %>
  </div>
</div>

<div style="margin-left: 20px; margin-top: 10px;" class="card col-10 hidden-sm-up">
  <div class="card-block">
    <h3 class="card-title"><%= content_tag(:div, user.nickname, class: "card-user_nickname") %></h3>
    <p class="card-text">한마디 : 
    <% if user.description.empty? %>
    <span style="color: blue">한마디를 적지 않으셨습니다.</span>
    <% else %>
    <%= user.description %>
    <% end %>
    </p>
    <%= link_to '쪽지 보내기', new_personal_message_path(receiver_id: user), class: "btn btn-primary" %>
  </div>
</div>

app/views/users/index.html.erb
<div class="board" style="background: url('/img/title_img_4.jpg') no-repeat center center/cover scroll;"><span style="color: white; background:rgba(0,0,0,0.6); padding: 10px; border-radius: 10px;"><%= link_to '강대인들', '/users', class: "board_title" %></span></div>

<% #경고메세지 출력 (아이디, 비밀번호 잘못 칠 시 등등...) %>
<% if alert %>
    <div class="alert alert-danger tlert-dismissible fade show text-center" style="padding: 10px; background-color: #FF4B5C; color: white; border-radius: 0; margin-bottom: 0; border: 0">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
    <% elsif notice %>
    <div class="alert alert-danger tlert-dismissible fade show text-center" style="padding: 10px; background-color: #43AC6A; color: white; border-radius: 0; margin-bottom: 0; border: 0">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
<% end %>

    <div class="container">
        <div class="row" style="margin-top: 30px;">
            <div class="col-3 col-sm-5"><h2>강대인</h2></div>
            <%= form_tag search_users_path, method: 'get', class: "ml-auto align-self-center d-flex flex-row" do %>
            <%= text_field_tag :q, params[:q], class: "form-control col-5 col-md-7", data: {toggle: "tooltip", placement: "bottom"}, title: "닉네임을 입력하세요." %>
            <%= submit_tag :검색, class: "btn btn-outline-success" %> <%= link_to '전체 목록', users_path, class: "btn btn-outline-info" if params[:q] %>
            <% end %>
        </div>
        
        <hr/>
        <% if @users.empty? %>
        <span align="center">
        <h3>
        OTL...
        해당 유저가 없습니다...
        </h3>
        </span>
        <% else %>
        <div class="row"><%= render @users %></div>
        <% end %>
        <div style="margin-top: 30px; margin-bottom: 100px;" class="d-flex flex-column">
            <%= paginate @users %>
        </div>
    </div>
</div>