config/routes.rb
Rails.application.routes.draw do


  root "home#index"

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  
  resources :bulletins do
    collection { get :search }
    resources :posts
    post "/posts/:post_id/good", to: "goods#good_toggle"
    post "/posts/:post_id/report", to: "reports#report_toggle"
  end

  get '/notifications/read_all' => 'notifications#read_all'

  resources :notifications

  devise_for :users
  
  resource :users, only: [:index] do
    collection { get :search }
  end

  get 'home/index'

  get '/home/update'

  get '/home/git'

  post '/tinymce_assets' => 'tinymce_assets#create'
  
  get "/knu/knu_world"
  
  post "/knu/key"
  
  ## 채팅 메세지 구현 By 상열 -----------------------------------------------------------------------------
  ## For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
  
  resources :users, only: [:index]
  resources :personal_messages, only: [:new, :create]
  resources :conversations, only: [:index, :show]

  
  get "/members/show" => "members#show"
  # --------------------------------------------------------------------------------------------------------

  resources :vote_comments
  resources :links do
    member do
      put "like", to:    "links#upvote"
      put "dislike", to: "links#downvote"
    end
  resources :vote_comments, only: [:create, :destroy]
  end


end

app/models/home.rb
class Home < ApplicationRecord
    paginates_per 5
    
    belongs_to :post
    belongs_to :bulletin, optional: true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @bulletins = Bulletin.all
    @allposts = Post.order("created_at DESC").first 5
    @topViewPosts = Post.all.sort {|post| post.impression_count}
    @topLikePosts = Post.all.sort {|post| post.goods.size}
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_bulletin.html.erb
<% if bulletin.empty? %>
    <h3 style="margin-top: 150px;">아직 개설된 게시판이 없습니다..</h3>
<% else %>
    <!-- 게시판 -->
      <% bulletin.each do |b| %>
          <%= render 'posts', title: b.title, posts: b.posts %>
          <div class="col-1 col-md-1"></div>
      <% end %>
<% end %>

app/views/home/_posts.html.erb
<div class="col-12 col-md-5 main_board" style="margin-top: 30px;">
  <span style="border-bottom: 2px solid gray; padding-bottom:10px;"><%= title %><span style="margin-left: 150px;">+</span></span>
  <% if posts.empty? %>
      <center><h3 style="margin-top: 50px; margin-bottom: 50px;">게시글이 없습니다..</h3></center>
  <% end %>
  <div style="margin-top: 15px;"></div>
  <% posts.each do |p| %>
      <% if user_signed_in? %>
          <%= link_to bulletin_post_path(p.bulletin, p) do %>
              <div class="col-md-10 board_title_etc" style="padding: 5px 5px 5px 5px;" bgcolor="white" onMouseOver="this.style.backgroundColor='#ECECEC'" onMouseOut="this.style.backgroundColor='#FFFFFF'">
                <%= content_tag(:div, p.title) %>
              </div>
          <% end %>
      <% else %>
          <%= link_to "#{bulletin_path(p.bulletin)}/posts" do %>
              <div class="col-md-10 board_title_etc" style="padding: 5px 5px 5px 5px" bgcolor="white" onMouseOver="this.style.backgroundColor='#ECECEC'" onMouseOut="this.style.backgroundColor='#FFFFFF'">
                <%= content_tag(:div, p.title) %>
              </div>
          <% end %>
      <% end %>
  <% end %>
</div>

app/views/home/git.html.erb
<div class="board" style="background: url('/img/title_img_2.jpg') no-repeat center center/cover scroll;"><span style="color: white; background:rgba(0,0,0,0.6); padding: 10px; border-radius: 10px;"><%= link_to ' Git!', '/home/git', class: "board_title fa fa-github-alt" %></span></div>
    <div class="container" style="margin-top:30px; margin-bottom: 100px;">
    <h1><i class="fa fa-github-alt" aria-hidden="true" style="margin-top: 30px;"></i> How to Use, Git ?</h1>
    <p><kbd><b style="color: yellow">Git 최초 시작 시</b></kbd> 깃 저장소를 만들어낸다.</p>
    <div class="bd-callout bd-callout-info">
        git init
    </div>
    <p><i class="fa fa-gg-circle" aria-hidden="true" style="margin-top: 20px;"></i> Push : 우리의 작업을 Git 자료실에 자료를 저장시킴.</p>
    <p>1. 우리의 작업에 대해 코딩 스크린샷 캡쳐(?)를 한다.</p>
    <div class="bd-callout bd-callout-info">
        git add .
    </div>
    <p>2. 우리의 작업을 Git 자료실에 올리기 이전, 메세지를 등록한다.</p>
    <div class="bd-callout bd-callout-info">
        git commit -m "내용"
    </div>
    <p><kbd><b style="color: yellow">첫 commit/pull이라면</b></kbd> 새로운 Git 원격접속 생성.</p>
    <div class="bd-callout bd-callout-info">
        git remote add origin https://github.com/kbs4674/Kangwon_community.git
    </div>
    <p>3. Git 자료실에 Push를 하여 지금 상태의 자료를 등록한다.<br/>(※참고로, 전에 있었다가 이번 작업으로 삭제된 자료가 있다면 그것 또한 적용되어, Git에서 해당 자료가 삭제된다.)</p>
    <div class="bd-callout bd-callout-info">
        git push -u origin master
        <div class="bd-callout bd-callout-danger">
           참고 : 강제 push하기 <br/>
           > git push -u origin +master
        </div>
    </div>
    
    <p><i class="fa fa-gg-circle" aria-hidden="true" style="margin-top: 20px;"></i> Pull : 우리의 작업을 Git 자료실에서 가져옴</p>
    <p><kbd><b style="color: yellow">시작 전</b></kbd> C9-Rails 튜토리얼로 작업 시 다음 명령어 작성 후 시작할 것.<br/>이 작업을 안하면 나중에 C9에서 Rails가 없어서 서버를 못 여는 등 골치아픈 일을 겪음.</p>
    <div class="bd-callout bd-callout-info">
        gem install rails --pre --no-ri --no-rdoc
        <div class="bd-callout bd-callout-danger">
           참고 : 레일즈 버전 변경을 원할 시 <br/>
           > gem install rails --version="버전"
        </div>
    </div>
    <p>다음 명령어를 입력</p>
    <div class="bd-callout bd-callout-info">
        git init<br/>
        git pull https://github.com/kbs4674/Kangwon_community.git
       <div class="bd-callout bd-callout-danger">
           참고 : <kbd>The following untracked working tree files would be overwritten by merge</kbd> 에러가 나올 시 <br/>
           > 명령어 입력창(터미널)에서 <kbd>git clean -d -fx ""</kbd> 입력
        </div>
    </div>
    <p><kbd><b style="color: yellow">마무리</b></kbd> C9-Rails 튜토리얼로 작업 시 다음 명령어 작성 후 마무리.<br/>현재 rails 상태는 빈 깡통 상태라서 이 작업이 필요함.</p>
    <div class="bd-callout bd-callout-info">
        bundle install
    </div>
    
    <p><i class="fa fa-gg-circle" aria-hidden="true" style="margin-top: 20px;"></i> 기타 명령어들</p>
    <p>- git Push/Pull 시 아이디/암호를 묻지 않음.</p>
    <div class="bd-callout bd-callout-info">
        git config --global credential.helper 'cache --timeout 7200'
    </div>
    <p>- C9 캐쉬 삭제</p>
    <div class="bd-callout bd-callout-info">
        git rm --cached .c9/ -r
    </div>
    <p>- 현재 내 Git의 상태를 보여줌</p>
    <div class="bd-callout bd-callout-info">
        git status
    </div>
    <p>- Git Branch</p>
    <div class="bd-callout bd-callout-info">
        <kbd style="color: yellow">Branch 목록</kbd><br/>
        git branch : Local의 Branch 목록을 봄.<br/>
        git branch -r : 원격저장소(Git 사이트 내 저장소)의 Branch 목록을 봄.<br/>
        gir branch -a : 모든 Branch 목록을 봄<br/><br/>
        <kbd style="color: yellow">Branch 생성/변경/삭제</kbd><br/>
        git branch -m 이름 new이름 : Branch 이름 변경.<br/>
        git branch -d 이름 : Branch 삭제.<br/>
        git branch 이름 : 새로운 Branch 생성<br/><br/>
        <kbd style="color: yellow">Main Branch 변경</kbd><br/>
        git checkout 이름 : 해당 Branch가 Main Branch가 된다.<br/>
        git checkout -d 이름 : 새 Branch를 만들자마자 바로 해당 Branch가 Main Branch가 된다.<br/>
    </div>
    <p>- Master Branch에서 [현재 있는 Branch이름] Branch 작업내역을 Merge 합니다!</p>
    <div class="bd-callout bd-callout-info">
        git checkout master<br/>
        git merge [현재 있는 Branch이름]
    </div>
    
    
    <h1><i class="fa fa-users" aria-hidden="true" style="margin-top: 30px;"></i> Team</h1>
    <div class="bd-callout bd-callout-info">
        김승한 / 이근식 / 서현석 / 김상열 / 김철민<br/>
    </div>
</div>

app/views/home/index.html.erb
<body class="home_gray">

<% #경고메세지 출력 (아이디, 비밀번호 잘못 칠 시 등등...) %>
  <% if alert %>
    <div class="alert alert-danger tlert-dismissible fade show text-center" style="padding: 10px; background-color: #FF4B5C; color: white; border-radius: 0; margin-bottom: 0; border: 0">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
    <% elsif notice %>
    <div class="alert alert-danger tlert-dismissible fade show text-center" style="padding: 10px; background-color: #43AC6A; color: white; border-radius: 0; margin-bottom: 0; border: 0">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
    <% else %>
  <% end %>
  <div style="margin-top: 10px;">&nbsp</div>

<div class="container">
  <div class="row">
    <%= render 'posts', title: '최다 조회수 게시물', posts: @topViewPosts %>
    <div class="col-1 col-md-1"></div>
    <%= render 'posts', title: '최다 좋아요 게시물', posts: @topLikePosts %>
    <div class="col-1 col-md-1"></div>
  </div>

  <div class="row">
    <%= render 'bulletin', bulletin: @bulletins %>
  </div>
</div>
</body>

app/views/home/update.html.erb
<div class="board" style="background: url('/img/title_img_2.jpg') no-repeat center center/cover scroll;"><span style="color: white; background:rgba(0,0,0,0.6); padding: 10px; border-radius: 10px;"><%= link_to '홈페이지 업데이트 내역', '/home/update', class: "board_title" %></span></div>
    <div class="container" style="margin-top:30px; margin-bottom: 100px;">
    <h1 style="border-bottom: 2px;"><i class="fa fa-check" aria-hidden="true"></i> 홈페이지 업데이트 내역 로그</h1>
    <div class="bd-callout bd-callout-warning">
        <b>17.7.04 이후 업데이트 내용 생략</b><br/>
            &nbsp· 업데이트 및 Rails 기능 구현법은 <a href="http://blog.naver.com/PostList.nhn?blogId=kbs4674&from=postList&categoryNo=78"><b><font color="#0066ff">여기</font></b></a>를 눌러서 참고
    </div>
    <div class="bd-callout bd-callout-warning">
        <b>17.6.24 <최신></b><br/>
            &nbsp· 홈페이지 최적화, 및 Git 사용법 Release, 게시판 재디자인
    </div>
    
    <div class="bd-callout bd-callout-warning">
        <b>17.5.28</b><br/>
            &nbsp· '좋아요' 기능 구현
    </div>
    
    <div class="bd-callout bd-callout-warning">
        <b>17.5.27</b><br/>
            &nbsp· 일부 UI디자인 수정
    </div>
    
    <div class="bd-callout bd-callout-warning">
        <b>17.5.26</b><br/>
            &nbsp· 자기 게시글은 자기만 삭제할 수 있게 하기<br/>
            &nbsp· 비정상적인 접근(예 : 자기 글이 아닌 게시글을 주소변경을 통해 임의접근)을 통한 삭제, 수정 시도 차단<br/>
            &nbsp· 기존의 <kbd>posts#new, posts#update</kbd> 에서 <kbd>＜form＞</kbd> 태그 방식을 폼헬퍼로 전환 (보안성 강화)<br/>
            &nbsp· 비정상적인 접근 시 에러메세지 출력<br/>
    </div>
    <div class="bd-callout bd-callout-warning">
        <b>~ 17.5.25</b><br/>
            &nbsp· 에디터 편집기<br/>
            &nbsp· 게시글 페이지 목록<br/>
            &nbsp· 로그인 한 사람만 게시판 등 접근 가능하게 접근권한 설정 (로그인 유무에 따른 구분)<br/>
            &nbsp· devise gem에 대한 한글화 패치 (완전히 끝나진 않음)<br/>
            &nbsp· Awesome 폰트 적용 [<a href="http://fontawesome.io/icons/" target="_blank"><font color="#0066ff">참고</font></a>]<br/>
    </div>
    
    <h1><i class="fa fa-pencil-square-o" aria-hidden="true" style="margin-top: 30px;"></i> 우리의 To do List</h1>
    <div class="bd-callout bd-callout-info">
        - 사진 업로드 연구 <br/>
        - 부진한 Mobile 브라우저 시점<br/>
        - postgress 연구 및 구현준비<br/>
        - rolify, cancancan을 이용한 회원권한 구현<br/>
        - 게시물 삭제 시 진짜 삭제되는게 아닌 hidden이 되도록 구현<br/>
            &nbsp· 예 : 레벨1 권한 게시글 주인 일반유저가 '삭제'버튼을 누르면 레벨1 권한의 모든 유저가 해당 게시글을 볼 수 없으나, <br/>
            실제로는 Admin 권한 유저는 해당 게시글을 볼 수 있음.<br/>
        - 알림 Gem 구현<br/>
            &nbsp· <a href="https://github.com/ledermann/unread" target="_blank"><font color="#0066ff">참고</font></a><br/>
        - 미완료된 devise 한글화 패치 나머지 끝내기<br/>
        - <kbd>posts#list</kbd>에서 게시글 제목(my_title) 옆에 해당 게시글의 댓글갯수 보이게 하기<br/>
        - <kbd>posts#show</kbd>에서 이전글, 다음글 기능 구현<br/>
        - 댓글기능 구현<br/>
           &nbsp· 댓글, 대댓글<br/>
        - 이미지 업로드 기능 구현<br/>
           &nbsp· 이 기능은 현재 우리가 쓰고있는 텍스트 편집기(TinyMCE)와 연동해서 사용하면 될 듯 하긴 함.<br/>
           &nbsp· 참고 - Git : TinyMCE <a href="https://github.com/spohlenz/tinymce-rails" target="_blank"><font color="#0066ff">클릭</font></a><br/>
        - 부트스트랩 : 모바일 보완 (PC버전에서 가로 스크롤창을 줄이면 문제점을 알 수 있음.)<br/>
        - 게시판 카테고리 기능 구현<br/>
            &nbsp· <a href="https://rorlab.gitbooks.io/railsguidebook/content/contents/walkthrough/model_association.html" target="_blank"><font color="#0066ff">참고</font></a><br/>
        - 홈페이지 짜잘한 디자인 보완 (카톡 썸네일 이미지, 파비콘, 홈페이지 UI 등..)<br/>
        - 우리모두 끝까지 살아남아서 '멋쟁이 사자처럼 5기' 수료증 받아내기<br/>
    </div>

    <h1><i class="fa fa-users" aria-hidden="true" style="margin-top: 30px;"></i> Team</h1>
    <div class="bd-callout bd-callout-info">
        김승한 / 이근식 / 서현석 / 김상열 / 김철민<br/>
    </div>
</div>