config/routes.rb
Rails.application.routes.draw do


  root "home#index"

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  
  resources :bulletins do
    collection { get :search }
    resources :posts
    post "/posts/:post_id/good", to: "goods#good_toggle"
    post "/posts/:post_id/report", to: "reports#report_toggle"
  end

  get '/notifications/read_all' => 'notifications#read_all'

  resources :notifications

  devise_for :users
  
  resource :users, only: [:index] do
    collection { get :search }
  end

  get 'home/index'

  get '/home/update'

  get '/home/git'

  post '/tinymce_assets' => 'tinymce_assets#create'
  
  get "/knu/knu_world"
  
  post "/knu/key"
  
  ## 채팅 메세지 구현 By 상열 -----------------------------------------------------------------------------
  ## For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
  
  resources :users, only: [:index]
  resources :personal_messages, only: [:new, :create]
  resources :conversations, only: [:index, :show]

  
  get "/members/show" => "members#show"
  # --------------------------------------------------------------------------------------------------------

  resources :vote_comments
  resources :links do
    member do
      put "like", to:    "links#upvote"
      put "dislike", to: "links#downvote"
    end
  resources :vote_comments, only: [:create, :destroy]
  end


end

app/models/post.rb
class Post < ApplicationRecord
  after_destroy :log_destroy_action
  acts_as_paranoid
  paginates_per 20
  resourcify
  
  has_many :impressions, :as=>:impressionable
  has_many :comments, dependent: :destroy
  has_many :homes
  belongs_to :bulletin, optional: true
  belongs_to :user
  has_many :goods
  has_many :gooded_users, through: :goods, source: :user
  has_many :reports
  has_many :reported_users, through: :reports, source: :user
  
  def log_destroy_action
    puts 'Post destroyed'
  end
  
  def impression_count
    impressions.size
  end

  def unique_impression_count
    # impressions.group(:ip_address).size gives => {'127.0.0.1'=>9, '0.0.0.0'=>1}
    # so getting keys from the hash and calculating the number of keys
    impressions.group(:ip_address).size.keys.length #TESTED
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :log_impression, :only=> [:show]
  before_action :set_bulletin
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  
  # 조회수 기록
  def log_impression
    @hit_post = Post.find(params[:id])
    # this assumes you have a current_user method in your authentication system
    @hit_post.impressions.create(ip_address: request.remote_ip,user_id:current_user.id)
  end

  def index
    @bulletin = Bulletin.find(params[:bulletin_id])
    @posts = Post.where(bulletin_id: @bulletin).order("created_at DESC").page params[:page]
  end

  def show
    @bulletin = Bulletin.find(params[:bulletin_id])
    @comments = @post.comments.page params[:page]
    #@pre = Post.find(params[:id - 1])
    #@next = Post.find([:id + 1])
  end

  def new
    @bulletin = Bulletin.find(params[:bulletin_id])
    @post = @bulletin.present? ? @bulletin.posts.new : Post.new
  end

  def edit
    @bulletin = Bulletin.find(params[:bulletin_id])
  end

  def create
    @bulletin = Bulletin.find(params[:bulletin_id])
    @post = @bulletin.present? ? @bulletin.posts.new(post_params) : Post.new(post_params)
    @post.num = 2
    @post.user_name = current_user.nickname
    @post.description = current_user.description
    @post.description_permission = current_user.description_permission

    respond_to do |format|
      if @post.save
        format.html { redirect_to (@bulletin.present? ? [@post.bulletin, @post] : @post), notice: '게시글이 성공적으로 작성되었습니다.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to (@bulletin.present? ? [@post.bulletin, @post] : @post), notice: '게시글이 성공적으로 수정되었습니다.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to (@bulletin.present? ? bulletin_posts_url : posts_url), notice: '게시글이 성공적으로 제거되었습니다.' }
      format.json { head :no_content }
    end
  end

  private
  def set_bulletin
    @bulletin = Bulletin.find(params[:bulletin_id]) if params[:bulletin_id].present?
  end

  def set_post
    if @bulletin.present?
      @post = @bulletin.posts.find(params[:id])
    else
      @post = Post.find(params[:id])
    end
  end

  def post_params
    params[:post][:user_id] = current_user.id
    params.require(:post).permit(:title, :content, :user_id) 
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
  <%= form_with(model: @bulletin.present? ? [@post.bulletin, @post] : @post, local: true) do |f| %>
  <div class="form-inputs">
      <%= f.label :제목 %>
      <%= f.text_field :title, id: :post_title, class: "form-control" %><br/>
      <%= f.label :내용 %>
      <%= tinymce %>
      <%= f.text_area :content, id: :post_content, class: "form-control tinymce", rows: "10" %>
      <% f.number_field :user_id %>
  </div>

  <center>
  <div class="form-actions" style="margin-top: 20px;">
    <%= f.button :글쓰기, class: "btn btn-primary" %>
<% end %>
<%= link_to '목록', (@bulletin.present? ? bulletin_posts_path(@bulletin) : posts_path), class: "btn btn-secondary" %>
</div>
</center>

app/views/posts/edit.html.erb
<% if mobile? %>
<div class="board_mobile" style="background: url('/img/title_img_1.jpg') no-repeat center center/cover scroll;"><span style="color: white; background:rgba(0,0,0,0.6); padding: 10px; border-radius: 10px;"><%= link_to "#{@bulletin.title}", "/bulletins/#{@bulletin.id}/posts", class: "board_title" %></span></div>
<% else %>
<div class="board" style="background: url('/img/title_img_1.jpg') no-repeat center center/cover scroll;"><span style="color: white; background:rgba(0,0,0,0.6); padding: 10px; border-radius: 10px;"><%= link_to "#{@bulletin.title}", "/bulletins/#{@bulletin.id}/posts", class: "board_title" %></span></div>
<% end %>

<% #경고메세지 출력 (아이디, 비밀번호 잘못 칠 시 등등...) %>
<% if alert %>
    <div class="alert alert-danger tlert-dismissible fade show text-center" style="padding: 10px; background-color: #FF4B5C; color: white; border-radius: 0; margin-bottom: 0; border: 0">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
    <% elsif notice %>
    <div class="alert alert-danger tlert-dismissible fade show text-center" style="padding: 10px; background-color: #43AC6A; color: white; border-radius: 0; margin-bottom: 0; border: 0">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
<% end %>

<div class="container" style="margin-top:30px; margin-bottom: 100px;">
  <div class="alert alert-info" role="alert">
    <strong><i class="fa fa-pencil-square-o" aria-hidden="true"></i> 게시글 수정</strong>
  </div>
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% if mobile? %>
<div class="board_mobile" style="background: url('/img/title_img_1.jpg') no-repeat center center/cover scroll;"><span style="color: white; background:rgba(0,0,0,0.6); padding: 10px; border-radius: 10px;"><%= link_to "#{@bulletin.title}", "/bulletins/#{@bulletin.id}/posts", class: "board_title" %></span></div>
<% else %>
<div class="board" style="background: url('/img/title_img_1.jpg') no-repeat center center/cover scroll;"><span style="color: white; background:rgba(0,0,0,0.6); padding: 10px; border-radius: 10px;"><%= link_to "#{@bulletin.title}", "/bulletins/#{@bulletin.id}/posts", class: "board_title" %></span></div>
<% end %>

<% #경고메세지 출력 (아이디, 비밀번호 잘못 칠 시 등등...) %>
<% if alert %>
    <div class="alert alert-danger tlert-dismissible fade show text-center" style="padding: 10px; background-color: #FF4B5C; color: white; border-radius: 0; margin-bottom: 0; border: 0">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
    <% elsif notice %>
    <div class="alert alert-danger tlert-dismissible fade show text-center" style="padding: 10px; background-color: #43AC6A; color: white; border-radius: 0; margin-bottom: 0; border: 0">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
<% end %>

<div class="container" style="margin-top:30px; margin-bottom: 100px;">
<span class="badge badge-pill badge-success"><i class="fa fa-clock-o" aria-hidden="true"></i> 현재 시간 </span> <span><%= Time.zone.now.strftime('%Y-%m-%d %H:%M:%S') %></span><br/><br/>

<div class="row hidden-xs-down">
<div style="padding: 10px 10px 10px 10px; border-bottom: 3px solid #D5D5D5; background: #EFEFEF;" class="col-1 col-sm-1 col-md-1 hidden-sm-down" align="center">No.</div>
<div style="padding: 10px 10px 10px 10px; border-bottom: 3px solid #D5D5D5; background: #EFEFEF;" class="col-3 col-sm-2 col-md-2" align="center">작성자</div>
<div style="padding: 10px 10px 10px 10px; border-bottom: 3px solid #D5D5D5; background: #EFEFEF;" class="col-4 col-sm-5 col-md-5" align="center">제목</div>
<div style="padding: 10px 10px 10px 10px; border-bottom: 3px solid #D5D5D5; background: #EFEFEF;" class="col-5 col-sm-3 col-md-2" align="center">작성시간</div>
<div style="padding: 10px 10px 10px 10px; border-bottom: 3px solid #D5D5D5; background: #EFEFEF;" class="col-5 col-sm-2 col-md-1" align="center">조회수</div>
<div style="padding: 10px 10px 10px 10px; border-bottom: 3px solid #D5D5D5; background: #EFEFEF;" class="col-5 col-sm-2 col-md-1 hidden-sm-down" align="center">좋아욧!</div>
</div>
<% if @posts.empty? %>
    <h2 class="text-center" style="margin-top: 30px;">게시글이 없습니다...</h2>
<% else %>
    <div style="margin-top: 5px;"></div>
    <div style="border-bottom: 2px solid gray;" class="row col-13 hidden-sm-up"></div>
    <% @posts.each do |post| %>
    <div class="row" bgcolor="white" onMouseOver="this.style.backgroundColor='#ECECEC'" onMouseOut="this.style.backgroundColor='#FFFFFF'">
        <% # [글 번호] 그리드 설정 : PC Only %>
        <div align="center" style="padding: 10px 10px 10px 10px; border-bottom: 1px solid gray;" class="col-1 col-sm-1 col-md-1 text-left text-sm-center hidden-sm-down"><%= post.id %></div>
        
        <% # [닉네임] 그리드 설정 : PC %>
        <div align="left" style="padding: 10px 10px 10px 10px; border-bottom: 1px solid gray;" class="col-sm-2 col-md-2 hidden-xs-down board_nickname_etc"> <%= post.user != nil ? post.user.nickname : post.user_name %></div>
        
        <% # [게시글 제목] 그리드 설정 : PC %>
        <div align="left" style="padding: 10px 10px 10px 10px; border-bottom: 1px solid gray;" class="col-sm-4 col-md-4 hidden-xs-down">
        <% if post.reports.size >= post.num %>
        <font color="#6E6E6E"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> 블라인드 된 게시글입니다.</font>
        <% else %>
            <%= link_to bulletin_post_path(post.bulletin, post) do %>
                <%= content_tag(:div, post.title, class: "board_title_etc") %>
            <% end %>
        <% end %>
        </div>
        
        <% # [게시글 제목] 그리드 설정 : 모바일 %>
        <div align="left" style="padding: 10px 10px 10px 10px; border-bottom: 1px solid gray;" class="col-6 hidden-sm-up">
        <% if post.reports.size >= post.num %>
        <font color="#6E6E6E"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> 블라인드 된 게시글입니다.</font>
        <% else %>
            <%= link_to bulletin_post_path(post.bulletin, post) do %>
                <%= content_tag(:div, post.title, class: "board_title_etc") %>
            <% end %>
        <% end %>
        </div>
        
        <% # [댓글 카운트] 그리드 설정 : 모바일 %>
        <div align="left" style="padding: 10px 10px 10px 10px; border-bottom: 1px solid gray;" class="col-1 hidden-sm-up">(<b><%= post.comments.count %></b>)</div>
        
        <% # [댓글 카운트] 그리드 설정 : PC %>
        <div align="right" style="padding: 10px 10px 10px 10px; border-bottom: 1px solid gray;" class="col-sm-1 col-md-1 hidden-xs-down">(<b><%= post.comments.count %></b>)</div>
        
        <% # [닉네임]  그리드 설정 : 모바일 %>
        <div align="center" style="padding: 10px 10px 10px 10px; border-bottom: 1px solid gray;" class="col-3 hidden-sm-up board_nickname_etc"><%= post.user != nil ? post.user.nickname : post.user_name %></div>
        
        <% # 시간 (PC / 모바일 공통) %>
        <div align="center" style="padding: 10px 10px 10px 10px; border-bottom: 1px solid gray;" class="col-4 col-sm-3 col-md-2 hidden-xs-down"><%= "#{time_ago_in_words(post.created_at)} 전" %></div>
        
        <% # 조회수 (PC / 모바일 공통) %>
        <div align="center" style="padding: 10px 10px 10px 10px; border-bottom: 1px solid gray;" class="col-3 col-sm-2 col-md-1 hidden-xs-down"><%= "#{post.unique_impression_count}" %></div>
        
        <% # [좋아요] 그리드 설정 : PC, 태블릿 크기 사이즈 X %>
        <div align="center" style="padding: 10px 10px 10px 10px; border-bottom: 1px solid gray;" class="col-md-1 hidden-sm-down"><i class="fa fa-thumbs-o-up" aria-hidden="true"></i> <%= post.goods.size %></div>
        
        <% # [좋아요] 그리드 설정 : 모바일 %>
        <div align="left" style="padding: 10px 10px 10px 10px; border-bottom: 1px solid gray;" class="col-2 hidden-sm-up"><i class="fa fa-thumbs-o-up" aria-hidden="true"></i> <%= post.goods.size %></div>
    </div>
    <% end %>
<% end %>
<br/>
<div align="right"><%= link_to "글 쓰기", new_bulletin_post_path(@bulletin), class: "btn btn-primary", style: "margin-top: -10px;" %></div>
<div class="d-flex flex-column", style="margin-bottom: 100px;">
  <%= paginate @posts, class: "text-center" %>
</div>
</div>

app/views/posts/new.html.erb
<% if mobile? %>
<div class="board_mobile" style="background: url('/img/title_img_1.jpg') no-repeat center center/cover scroll;"><span style="color: white; background:rgba(0,0,0,0.6); padding: 10px; border-radius: 10px;"><%= link_to "#{@bulletin.title}", "/bulletins/#{@bulletin.id}/posts", class: "board_title" %></span></div>
<% else %>
<div class="board" style="background: url('/img/title_img_1.jpg') no-repeat center center/cover scroll;"><span style="color: white; background:rgba(0,0,0,0.6); padding: 10px; border-radius: 10px;"><%= link_to "#{@bulletin.title}", "/bulletins/#{@bulletin.id}/posts", class: "board_title" %></span></div>
<% end %>

<% #경고메세지 출력 (아이디, 비밀번호 잘못 칠 시 등등...) %>
<% if alert %>
    <div class="alert alert-danger tlert-dismissible fade show text-center" style="padding: 10px; background-color: #FF4B5C; color: white; border-radius: 0; margin-bottom: 0; border: 0">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
    <% elsif notice %>
    <div class="alert alert-danger tlert-dismissible fade show text-center" style="padding: 10px; background-color: #43AC6A; color: white; border-radius: 0; margin-bottom: 0; border: 0">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
<% end %>

<div class="container" style="margin-top:30px; margin-bottom: 100px;">
<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<% if mobile? %>
<div class="board_mobile" style="background: url('/img/title_img_1.jpg') no-repeat center center/cover scroll;"><span style="color: white; background:rgba(0,0,0,0.6); padding: 10px; border-radius: 10px;"><%= link_to "#{@bulletin.title}", "/bulletins/#{@bulletin.id}/posts", class: "board_title" %></span></div>
<% else %>
<div class="board" style="background: url('/img/title_img_1.jpg') no-repeat center center/cover scroll;"><span style="color: white; background:rgba(0,0,0,0.6); padding: 10px; border-radius: 10px;"><%= link_to "#{@bulletin.title}", "/bulletins/#{@bulletin.id}/posts", class: "board_title" %></span></div>
<% end %>

<% #경고메세지 출력 (아이디, 비밀번호 잘못 칠 시 등등...) %>
<% if alert %>
    <div class="alert alert-danger tlert-dismissible fade show text-center" style="padding: 10px; background-color: #FF4B5C; color: white; border-radius: 0; margin-bottom: 0; border: 0">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
    <% elsif notice %>
    <div class="alert alert-danger tlert-dismissible fade show text-center" style="padding: 10px; background-color: #43AC6A; color: white; border-radius: 0; margin-bottom: 0; border: 0">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
<% end %>

<div class="container" style="margin-top:30px; margin-bottom: 100px;">
    <% if @post.reports.size >= @post.num %>
    <font color="red">블라인드 처리된 게시글입니다.</font><hr/>
    <% else %>
    <h4 class="col-12" style="padding: 0px;"><%= @post.title %></h4>
    
    <div class="row">
      <% # [그리드] PC, 모바일 공통에서 볼 경우 : 닉네임 %>
      <div class="col-4"><%= @post.user != nil ? @post.user.nickname : @post.user_name %></div>
      <% # [그리드] Only 모바일 에서 볼 경우 : 글 작성시간 %>
      <div class="col-8 " align="right"><span><%= @bulletin.created_at.in_time_zone("Asia/Seoul").strftime('%Y-%m-%d %H:%M') %></span>
        |<i class="fa fa-eye" aria-hidden="true" style="margin-left: 15px;"></i> <%= "#{@post.unique_impression_count}" %></div>
    </div>
    <hr/>
    <% end %>
    
    <div style="float: right; font-size: 15px">
    <% # 좋아요 기능 로그인 여부에 따라 다른 좋아요 버튼, 좋아요 갯수는 likes.size 메서드로 출력 %>
    <% if current_user.is_good?(@post) %>
    <%= @post.goods.size %> 명이 좋아합니다.
    <%= link_to " 좋아욧 취소", "/bulletins/#{@bulletin.id}/posts/#{@post.id}/good", class: "btn btn-danger btn-sm fa fa-times", :method => :post %>
    <% else %>
    <%= @post.goods.size %> 명이 좋아합니다.
    <%= link_to " 좋아욧!", "/bulletins/#{@bulletin.id}/posts/#{@post.id}/good", class: " btn btn-info btn-sm fa fa-thumbs-o-up", :method => :post %>
    <% end %>
    </div>
      
    <div style="float: left">  
    <% if current_user.is_report?(@post) %>
      <i class="fa fa-exclamation" aria-hidden="true"></i> 블라인드 요청 완료
    <% elsif @post.reports.size >= @post.num %>
      <i class="fa fa-exclamation" aria-hidden="true"></i> 블라인드 처리된 글임.
    <% else %>
      <%= link_to " 신고", "", data: { toggle: "collapse", target: "#collapseExample" }, aria: { expanded: "false", controls: "collapseExample" }, class: "badge badge-pill badge-danger fa fa-scissors" %>
      <div class="collapse" id="collapseExample">
        <div class="card card-block">
          정말 이 글을 블라인드 요청 하시겠습니까? 취소 할 수 없습니다. <span>
           <%= link_to "블라인드 요청", "/bulletins/#{@bulletin.id}/posts/#{@post.id}/report", class: "badge badge-pill badge-danger fa fa-scissors", :method => :post %></span>
        </div>
      </div>
      <% end %>
    </div>
    
    <% if @post.reports.size >= @post.num %>
    <br/><br/><br/><font color="red"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> 블라인드 된 게시글입니다.</font><br/>
    <% else %>
    <br/><br/><br/><%= content_tag(:div, @post.content.html_safe, :class => "panel-body") %>
    <% end %>
    
    <br/><hr/>
    
    <div class= "row">
        <div class="col-7 col-md-6" align="left">
            <%= link_to '목록', "/bulletins/#{@bulletin.id}/posts", class: "btn btn-secondary btn-sm" %>
            <% if can? :update, @post %>
            <%= link_to '수정', (@bulletin.present? ? edit_bulletin_post_path(@bulletin)  : edit_post_path(@post)), class: "btn btn-secondary btn-sm" %>
            <% end %>
            <% if can? :destroy, @post %>
            <%= link_to "삭제", (@bulletin.present? ? [@post.bulletin, @post] : @post), method: :delete, data: { confirm: '진짜로 지울건가요???' }, class: "btn btn-secondary btn-sm" %>
            <% end %>
        </div>
        <div class="col-5 col-md-6" align="right">
          <%= link_to '글 쓰기', (@bulletin.present? ?  new_bulletin_post_path(@bulletin) : new_post_path), class: "btn btn-secondary btn-sm", align: "right" %>
        </div>
    </div>
    
    <% if @post.reports.size >= @post.num %>
    <font color="red"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> 블라인드 처리된 게시글에서는 댓글이 공개되지 않습니다.<br/></font>
    <% else %>
    <%= render "comments/comments" %>
    <% end %>
  
    <div style="margin-top: 30px;">
    <% if @post.id == 0 %>
    <%= link_to "▼ 다음글  |  #{@post.title}-1", "/bulletins/#{@bulletin.id}/posts/#{@post.id}-1" %>
    <% else %>
    <%= link_to "▲ 이전글  |  #{@post.title}+1", "/bulletins/#{@bulletin.id}/posts/#{@post.id}" %><br>
    <%= link_to "▼ 다음글  |  #{@post.title}-1", "/bulletins/#{@bulletin.id}/posts/#{@post.id}-1" %>
    <% end %>
    </div>
  

</div>